# Generated by Django 2.2.27 on 2022-08-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_id', models.CharField(max_length=100)),
                ('contest_id', models.CharField(max_length=100)),
                ('selection_id', models.CharField(max_length=100)),
                ('tally', models.CharField(max_length=100)),
            ],
        ),
    ]
