# Generated by Django 2.2.27 on 2022-08-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spoiled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_id', models.CharField(blank=True, max_length=500, null=True)),
                ('contest_id', models.CharField(blank=True, max_length=500, null=True)),
                ('selection_id', models.CharField(blank=True, max_length=500, null=True)),
                ('tally', models.CharField(blank=True, max_length=500, null=True)),
                ('ledger_start_transaction_id', models.BigIntegerField()),
                ('ledger_end_transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('ledger_start_sequence_number', models.BigIntegerField()),
                ('ledger_end_sequence_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spoiled',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ballot_id', models.CharField(blank=True, max_length=500, null=True)),
                ('style_id', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=500, null=True)),
                ('ledger_start_transaction_id', models.BigIntegerField()),
                ('ledger_end_transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('ledger_start_sequence_number', models.BigIntegerField()),
                ('ledger_end_sequence_number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submitted',
                'managed': False,
            },
        ),
    ]
